Repository qaml-bootcamp-java-selenium-jul2022/qaml_commandLine, pull requests merged in 2022-08, with the labels that each got.

#9 Ejercicio Zoologico y Circulo
  src/calculocirculo/Circulo.java
  src/calculocirculo/MainCirculo.java
  src/zoologico/Acuario.java
  src/zoologico/Animales.java
  src/zoologico/Aviario.java
  src/zoologico/Delfin.java
  src/zoologico/HabitatTerrestre.java
  src/zoologico/Leon.java
  src/zoologico/MainZoologico.java
  src/zoologico/Pavorreal.java
  src/zoologico/Reptilario.java
  src/zoologico/SerpienteCascabel.java
Labels: Gilberto

#11 Ejercicio en clase sobre Strings
  src/EjerciciosString/Main.java
Labels: Alvaro

#15 Ejercicio en clase override toString() & equals()
  src/EjercicioVideojuego/Elfo.java
  src/EjercicioVideojuego/MainVideojuego.java
  src/EjerciciosString/MainEjerciciosStrings.java
Labels: Facilitadora del curso

#12 Feature/ejercicio string en equipo
  src/EjerciciosString/MainEjerciciosStrings.java
Labels: Judith

#16 Ejercicios de colecciones en clase
  src/EjerciciosColecciones/MainEjerciciosColecciones.java
  src/EjerciciosString/MainEjerciciosStrings.java
Labels: Facilitadora del curso
